### ISSUE TITLE
Nightly Build links are broken on actual website

### ISSUE THREAD

**Issue by cristallium** [apache/royale-website#4]
Hi

Nightly Build links are broken on actual website (both JS Only and JS + SWf)

http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/

http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/

Where to download it ?

Regards

**Comment by carlosrovira** [comment]
HI Fred,

URL has changed and now are:

http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/

http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/

(just adding a "2" for "apacheroyaleci")

I updated in presite. Will be updating public site soon.

Thanks!

**Comment by carlosrovira** [comment]
one more thing, is that due to some Apache rules, nightly builds section in download page will be moved to "get involved" page in next update
